### ISSUE TITLE
[API] dislike location.

### ISSUE THREAD

**Issue by toan12520447** [toan12520447/demo-server#15]
after i like location, i double click  that(i am doing dislike location).
because i need API dislike location.
@HoangTranUit let me know if you have any question.

**Comment by toan12520447** [comment]
i don't find route API dislike.
@HoangTranUit please help me recheck.

**Comment by toan12520447** [comment]
it may be the last task before i will present with my instructors.
hopefully tonight or tomorrow you will complite this.

**Comment by HoangTranUit** [comment]
#15 done
