### ISSUE TITLE
the location data need change a few fields.

### ISSUE THREAD

**Issue by toan12520447** [toan12520447/demo-server#17]
when i create a location.
method: POST.
route : Location.
body :
{
    "name" : "Vincom Q9",
    "describe": "Khu Du lịch Văn hóa Suối Tiên là một khu liên hợp vui chơi giải trí tại Quận 9, Thành phố Hồ Chí Minh. Kiểu cách kiến trúc và các thể loại vui chơi được gắn lồng vào các hình ảnh lịch sử và truyền thuyết Việt Nam như Lạc Long Quân - Âu Cơ, Vua Hùng, sự tích trăm trứng, Sơn Tinh Thủy Tinh, sự tích bánh chưng bánh dày, sự tích quả dưa hấu, chín tầng địa ngục, tứ linh hội tụ Long - Lân - Quy - Phụng, công viên giải trí dưới nước, đặc biệt là biển Tiên Đồng, biển nhân tạo đầu tiên ở Việt Nam(hiện nay có biển nhân tạo tại khu du lịch Đại Nam Văn Hiến). Đây là địa điểm thu hút khá lớn lượng khách vui chơi giải trí của Thành phố Hồ Chí Minh và các du khách địa phương khác đến.",
    "time" : "8:00 - 18:00",
    "price" : "100.000 - 200.000",
    "location" : {
        "address" : "Quận 9, Thành phố Hồ Chí Minh.",
        "lat": "10.8657892",
        "lon" : "106.8021649"
    },
    "category":"57d37d041ef51630040b85a4"
}

the time field should change to NSString -> object like location. please look at image below.
"time":{
"monday": ""
"Tuesday":""
"Wednesday":""	
"Thursday":""	
"Friday":""	
"Saturday":""	
"Sunday":""
}
<img width="299" alt="screen shot 2016-09-14 at 10 07 45 pm" src="https://cloud.githubusercontent.com/assets/15081435/18517888/22931a3c-7ac8-11e6-9ac8-e3a0045857b7.png">

i will handle the field "time" so as.
what about you?

**Comment by toan12520447** [comment]
i am looking forward to your feeback about situation.

**Comment by HoangTranUit** [comment]
day and day off for time field

**Comment by toan12520447** [comment]
ok!
 @HoangTranUit  please let me know how long to add this.
