### ISSUE TITLE
[urgent]   the fields "time" when i create "location" not correct.

### ISSUE THREAD

**Issue by toan12520447** [toan12520447/demo-server#20]
i'm using route create location.
body data:
 "time" : {
      "day":"7h00 - 17h00",
      "dayoff":"7h00 - 18h00"
    },
i got data server response is ::
"time": {
      "day": "7h00 - 17h00"
    },
at the moment, it is missing dayoff.
please help me confirm about this issue.

**Comment by toan12520447** [comment]
i have review code lastest you have addition a field dayoff, no matter how server not respond about it.

**Comment by HoangTranUit** [comment]
[20] It's dayOff not dayoff

**Comment by toan12520447** [comment]
ok, i got it.
